#!/usr/bin/env python3

def char_count(str):
    char_list = set(str)
    for char in char_list:
        print(char, str.count(char))

if __name__ == '__main__':

    s = input("Enter a string: ")

    char_count(s)
    
    
    

#!/usr/bin/env python3:


def char_count(str):

    chardict = {}
    
    for char in str:
        c = chardict.get(char)
        if c is None:
            chardict[char] = 1
        else:
            chardict[char] += 1
    
    for a,b in chardict.items():

        print(a, b)


if __name__ == '__main__':

    s = input("Enter a String:")
    char_count(s)
    

#!/usr/bin/env python3:

def char_count(str):

    countdict = {}
    for char in str:
        countdict[char] = countdict.get(char,0) + 1
    for keys,values in countdict.items():
        print(keys,values)
if __name__ == '__main__':
    s = input("Enter a string:")
    char_count(s)

